### ISSUE TITLE
Estimate fails when person who created the session reveals a vote

### ISSUE THREAD

**Issue by indiraraghavan1986** [microsoft/azure-boards-estimate#13]
Unable to view the votes by the person who hits Reveal button. 
![image](https://user-images.githubusercontent.com/46982290/128241549-b5f59adb-8579-4af8-bb2f-2ceb363df8f2.png)

**Comment by MOlausson** [comment]
Thanks @indiraraghavan1986, we've working on this now.

**Comment by MOlausson** [comment]
We released an update that should resolve this (2.3.1). Closing this issue but feel free to reopen.

**Comment by danieldorsey3** [comment]
I'm still getting blank screen when Reveal button is selected - unable to view the votes by the person. Please advise

**Comment by danieldorsey3** [comment]
to add...  some estimates are working, but getting blank screen occasionally, not sure what is causing the issue.

**Comment by danieldorsey3** [comment]
@MOlausson  any update on status or any additional info needed to help review?

**Comment by MOlausson** [comment]
@danieldorsey3 can you check if you see any errors in the network or console log in the browser's developer tools (F12)?

**Comment by danieldorsey3** [comment]
@MOlausson
react-dom.production.min.js:4408 TypeError: Cannot read properties of undefined (reading 'identifier')
    at t.n.renderCard (workItemView.tsx:200)
    at workItemView.tsx:133
    at Array.map (<anonymous>)
    at t.value (workItemView.tsx:127)
    at Oi (react-dom.production.min.js:3785)
    at Pi (react-dom.production.min.js:3776)
    at Di (react-dom.production.min.js:3960)
    at Ka (react-dom.production.min.js:5514)
    at Ga (react-dom.production.min.js:5536)
    at Os (react-dom.production.min.js:5958)
da @ react-dom.production.min.js:4408
n.callback @ react-dom.production.min.js:4773
oa @ react-dom.production.min.js:4271
ra @ react-dom.production.min.js:4259
za @ react-dom.production.min.js:4999
qa @ react-dom.production.min.js:5123
(anonymous) @ react-dom.production.min.js:5975
t.unstable_runWithPriority @ scheduler.production.min.js:274
Rs @ react-dom.production.min.js:5974
Os @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
Ns @ react-dom.production.min.js:6020
kn @ react-dom.production.min.js:1737
react-dom.production.min.js:5940 Uncaught TypeError: Cannot read properties of undefined (reading 'identifier')
    at t.n.renderCard (workItemView.tsx:200)
    at workItemView.tsx:133
    at Array.map (<anonymous>)
    at t.value (workItemView.tsx:127)
    at Oi (react-dom.production.min.js:3785)
    at Pi (react-dom.production.min.js:3776)
    at Di (react-dom.production.min.js:3960)
    at Ka (react-dom.production.min.js:5514)
    at Ga (react-dom.production.min.js:5536)
    at Os (react-dom.production.min.js:5958)

**Comment by danieldorsey3** [comment]
@MOlausson
This is the complete log with warning from point of opening Estimate >>

Error with Permissions-Policy header: Unrecognized feature: 'interest-cohort'.
DevTools failed to load source map: Could not load content for https://amcdn.msftauth.net/meInlineBackCompat.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://amcdn.msftauth.net/scripts/me/MeControl/10.21162.3/en-US/meBoot.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
meCore.min.js:1 Cross-Origin Read Blocking (CORB) blocked cross-origin response https://web.vortex.data.microsoft.com/collect/v1 with MIME type application/json. See https://www.chromestatus.com/feature/5629709824032768 for more details.
Dt @ meCore.min.js:1
Y @ me?partner=vsts-social&amp;market=en-us:1
setTimeout (async)
K @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
ue @ me?partner=vsts-social&amp;market=en-us:1
t.enhanceTelemetry @ meCore.min.js:1
(anonymous) @ meBoot.min.js:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
t @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
t @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
t @ me?partner=vsts-social&amp;market=en-us:1
c @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
xe.then @ me?partner=vsts-social&amp;market=en-us:1
c @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
je @ me?partner=vsts-social&amp;market=en-us:1
xe @ me?partner=vsts-social&amp;market=en-us:1
xe.all @ me?partner=vsts-social&amp;market=en-us:1
e @ me?partner=vsts-social&amp;market=en-us:1
Xe @ me?partner=vsts-social&amp;market=en-us:1
t.onload @ me?partner=vsts-social&amp;market=en-us:1
load (async)
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
je @ me?partner=vsts-social&amp;market=en-us:1
xe @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
He @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ meBoot.min.js:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
t @ me?partner=vsts-social&amp;market=en-us:1
n @ meBoot.min.js:1
load (async)
zt @ meBoot.min.js:1
Xt @ meBoot.min.js:1
Pe @ meBoot.min.js:1
nt.getLoader @ meBoot.min.js:1
nt.componentDidMount @ meBoot.min.js:1
C @ meBoot.min.js:1
R @ meBoot.min.js:1
I @ meBoot.min.js:1
t.init @ meBoot.min.js:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
t @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
t @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
ke @ me?partner=vsts-social&amp;market=en-us:1
De @ me?partner=vsts-social&amp;market=en-us:1
t @ me?partner=vsts-social&amp;market=en-us:1
c @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
Promise.then (async)
p.Promise.p.Promise.toString.indexOf.xe._immediateFn @ me?partner=vsts-social&amp;market=en-us:1
_e @ me?partner=vsts-social&amp;market=en-us:1
xe.then @ me?partner=vsts-social&amp;market=en-us:1
c @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
je @ me?partner=vsts-social&amp;market=en-us:1
xe @ me?partner=vsts-social&amp;market=en-us:1
xe.all @ me?partner=vsts-social&amp;market=en-us:1
e @ me?partner=vsts-social&amp;market=en-us:1
Xe @ me?partner=vsts-social&amp;market=en-us:1
t.onload @ me?partner=vsts-social&amp;market=en-us:1
load (async)
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
je @ me?partner=vsts-social&amp;market=en-us:1
xe @ me?partner=vsts-social&amp;market=en-us:1
(anonymous) @ me?partner=vsts-social&amp;market=en-us:1
He @ me?partner=vsts-social&amp;market=en-us:1
rn @ me?partner=vsts-social&amp;market=en-us:1
En @ me?partner=vsts-social&amp;market=en-us:1
_loadMeControlComponent @ ms.vss-tfs-web.frame-content.es6.mWCDy5Jb2V6bz7k_.min.js:1
e.loadScripts.then.t.endScenario.status @ ms.vss-tfs-web.frame-content.es6.mWCDy5Jb2V6bz7k_.min.js:1
Promise.then (async)
_onLoadMeControlScript @ ms.vss-tfs-web.frame-content.es6.mWCDy5Jb2V6bz7k_.min.js:1
r @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
notify @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
_notify @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
fireEvent @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
s @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
i @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
Ft @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
Jn @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
(anonymous) @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
unstable_runWithPriority @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
bt @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
Cr @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
mr @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
Ku @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
Yr @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
(anonymous) @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
yr @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
Zr @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
e.render @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
renderPage @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
(anonymous) @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
r @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
notify @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
set value @ ms.vss-web.core-content.es6.ZKCGuoKco__BHji7u.min.js:1
(anonymous) @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
DevTools failed to load source map: Could not load content for https://amcdn.msftauth.net/scripts/me/MeControl/10.21162.3/en-US/meCore.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://amcdn.msftauth.net/Scripts/dist/src/MeProxy.min.js.map: Fetch through target failed: Session is unregistering, can't dispatch pending call to Network.loadNetworkResource; Fallback: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1 GET https://extmgmt.dev.azure.com/AIZ-GL/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/sessions/Documents 404 (Not Found)
t.<computed>.issueRequest @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
async function (async)
t.<computed>.issueRequest @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
_issueRequest @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
async function (async)
_issueRequest @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
(anonymous) @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
Promise.then (async)
beginRequest @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
getDocumentsByName @ ms.vss-features.ext-services-content.es6.PEPzI29OHQYfkK4g.min.js:1
getDocuments @ ms.vss-features.ext-services-content.es6.PEPzI29OHQYfkK4g.min.js:1
proxyFunctions.<computed> @ ms.vss-web.ext-content.es6.2DCMZ0FMPSP__vv0b.min.js:1
invokeMethod @ ms.vss-web.ext-content.es6.2DCMZ0FMPSP__vv0b.min.js:1
onMessage @ ms.vss-web.ext-content.es6.2DCMZ0FMPSP__vv0b.min.js:1
_handleMessageReceived @ ms.vss-web.ext-content.es6.2DCMZ0FMPSP__vv0b.min.js:1
ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1 GET https://extmgmt.dev.azure.com/AIZ-GL/_apis/ExtensionManagement/InstalledExtensions/ms-devlabs/estimate/Data/Scopes/Default/Current/Collections/EstimationSessions/Documents 404 (Not Found)
t.<computed>.issueRequest @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
async function (async)
t.<computed>.issueRequest @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
_issueRequest @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
async function (async)
_issueRequest @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
(anonymous) @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
Promise.then (async)
beginRequest @ ms.vss-web.platform-content.es6.ynG3UqEHcpj3i33b.min.js:1
getDocumentsByName @ ms.vss-features.ext-services-content.es6.PEPzI29OHQYfkK4g.min.js:1
getDocuments @ ms.vss-features.ext-services-content.es6.PEPzI29OHQYfkK4g.min.js:1
proxyFunctions.<computed> @ ms.vss-web.ext-content.es6.2DCMZ0FMPSP__vv0b.min.js:1
invokeMethod @ ms.vss-web.ext-content.es6.2DCMZ0FMPSP__vv0b.min.js:1
onMessage @ ms.vss-web.ext-content.es6.2DCMZ0FMPSP__vv0b.min.js:1
_handleMessageReceived @ ms.vss-web.ext-content.es6.2DCMZ0FMPSP__vv0b.min.js:1
react-dom.production.min.js:4408 TypeError: Cannot read properties of undefined (reading 'identifier')
    at t.n.renderCard (workItemView.tsx:200)
    at workItemView.tsx:133
    at Array.map (<anonymous>)
    at t.value (workItemView.tsx:127)
    at Oi (react-dom.production.min.js:3785)
    at Pi (react-dom.production.min.js:3776)
    at Di (react-dom.production.min.js:3960)
    at Ka (react-dom.production.min.js:5514)
    at Ga (react-dom.production.min.js:5536)
    at Os (react-dom.production.min.js:5958)
da @ react-dom.production.min.js:4408
n.callback @ react-dom.production.min.js:4773
oa @ react-dom.production.min.js:4271
ra @ react-dom.production.min.js:4259
za @ react-dom.production.min.js:4999
qa @ react-dom.production.min.js:5123
(anonymous) @ react-dom.production.min.js:5975
t.unstable_runWithPriority @ scheduler.production.min.js:274
Rs @ react-dom.production.min.js:5974
Os @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
Ns @ react-dom.production.min.js:6020
kn @ react-dom.production.min.js:1737
react-dom.production.min.js:5940 Uncaught TypeError: Cannot read properties of undefined (reading 'identifier')
    at t.n.renderCard (workItemView.tsx:200)
    at workItemView.tsx:133
    at Array.map (<anonymous>)
    at t.value (workItemView.tsx:127)
    at Oi (react-dom.production.min.js:3785)
    at Pi (react-dom.production.min.js:3776)
    at Di (react-dom.production.min.js:3960)
    at Ka (react-dom.production.min.js:5514)
    at Ga (react-dom.production.min.js:5536)
    at Os (react-dom.production.min.js:5958)

**Comment by MOlausson** [comment]
@danieldorsey3 thanks for the details, I'm reopening the issue and we'll investigate.

**Comment by danieldorsey3** [comment]
Any update on status - @MOlausson
Thanks

**Comment by MOlausson** [comment]
@danieldorsey3 are you still experience this problem?

**Comment by danieldorsey3** [comment]
We haven’t use the board this week, but will be next week and will advise.
Thanks

From: Mathias Olausson ***@***.***>
Sent: Sunday, December 5, 2021 2:01 PM
To: microsoft/azure-boards-estimate ***@***.***>
Cc: Daniel Dorsey ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/azure-boards-estimate] Estimate fails when person who created the session reveals a vote (#13)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________

@danieldorsey3<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_danieldorsey3&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=_YjsN32xR7U0MJwlwfR4sI6m2FU1pTmlLO-rc12Rufo&e=> are you still experience this problem?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_azure-2Dboards-2Destimate_issues_13-23issuecomment-2D986282456&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=Mj1A6U2rRdVRswXYo1BqFS93M9bFjFpXEFPWOI0NuwA&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATB4AYXV5WAGWVQGJGX27DTUPOZGTANCNFSM5BR2H4BA&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=YQQEcEVsh5DA5059J33WQGX4xcEB98Vh0SX2rd-zR6c&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=_VZHNf9JS499ehPzltoIhMOxxt3_X_0NM9ezpkGk4uw&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=YTevS5Kk1BYJKI0CW499xv2PEqydV3z3C1bTV4nfIOo&e=>.

**********************************************************************
This e-mail message and all attachments transmitted with it may contain legally privileged and/or confidential information intended solely for the use of the addressee(s). If the reader of this message is not the intended recipient, you are hereby notified that any reading, dissemination, distribution, copying, forwarding or other use of this message or its attachments is strictly prohibited. If you have received this message in error, please notify the sender immediately and delete this message and all copies and backups thereof. Thank you.

**Comment by danieldorsey3** [comment]
We were able to successfully use Estimate board without issue.
Thanks
@MOlausson<https://github.com/MOlausson>


From: Mathias Olausson ***@***.***>
Sent: Sunday, December 5, 2021 2:01 PM
To: microsoft/azure-boards-estimate ***@***.***>
Cc: Daniel Dorsey ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/azure-boards-estimate] Estimate fails when person who created the session reveals a vote (#13)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________

@danieldorsey3<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_danieldorsey3&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=_YjsN32xR7U0MJwlwfR4sI6m2FU1pTmlLO-rc12Rufo&e=> are you still experience this problem?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_azure-2Dboards-2Destimate_issues_13-23issuecomment-2D986282456&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=Mj1A6U2rRdVRswXYo1BqFS93M9bFjFpXEFPWOI0NuwA&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATB4AYXV5WAGWVQGJGX27DTUPOZGTANCNFSM5BR2H4BA&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=YQQEcEVsh5DA5059J33WQGX4xcEB98Vh0SX2rd-zR6c&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=_VZHNf9JS499ehPzltoIhMOxxt3_X_0NM9ezpkGk4uw&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=YTevS5Kk1BYJKI0CW499xv2PEqydV3z3C1bTV4nfIOo&e=>.

**********************************************************************
This e-mail message and all attachments transmitted with it may contain legally privileged and/or confidential information intended solely for the use of the addressee(s). If the reader of this message is not the intended recipient, you are hereby notified that any reading, dissemination, distribution, copying, forwarding or other use of this message or its attachments is strictly prohibited. If you have received this message in error, please notify the sender immediately and delete this message and all copies and backups thereof. Thank you.

**Comment by danieldorsey3** [comment]
We got the white screen again after trying to Reveal after team added their vote, so issue doesn’t appear to have been fixed. Please review and advise.

From: Mathias Olausson ***@***.***>
Sent: Sunday, December 5, 2021 2:01 PM
To: microsoft/azure-boards-estimate ***@***.***>
Cc: Daniel Dorsey ***@***.***>; Mention ***@***.***>
Subject: [External] Re: [microsoft/azure-boards-estimate] Estimate fails when person who created the session reveals a vote (#13)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________

@danieldorsey3<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_danieldorsey3&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=_YjsN32xR7U0MJwlwfR4sI6m2FU1pTmlLO-rc12Rufo&e=> are you still experience this problem?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_microsoft_azure-2Dboards-2Destimate_issues_13-23issuecomment-2D986282456&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=Mj1A6U2rRdVRswXYo1BqFS93M9bFjFpXEFPWOI0NuwA&e=>, or unsubscribe<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ATB4AYXV5WAGWVQGJGX27DTUPOZGTANCNFSM5BR2H4BA&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=YQQEcEVsh5DA5059J33WQGX4xcEB98Vh0SX2rd-zR6c&e=>.
Triage notifications on the go with GitHub Mobile for iOS<https://urldefense.proofpoint.com/v2/url?u=https-3A__apps.apple.com_app_apple-2Dstore_id1477376905-3Fct-3Dnotification-2Demail-26mt-3D8-26pt-3D524675&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=_VZHNf9JS499ehPzltoIhMOxxt3_X_0NM9ezpkGk4uw&e=> or Android<https://urldefense.proofpoint.com/v2/url?u=https-3A__play.google.com_store_apps_details-3Fid-3Dcom.github.android-26referrer-3Dutm-5Fcampaign-253Dnotification-2Demail-2526utm-5Fmedium-253Demail-2526utm-5Fsource-253Dgithub&d=DwMCaQ&c=59WElTcIEwbBjXQe6gMr9RyqhrzJYRWAhv5h0b8rPQw&r=yll5qDCv6Y0n9jUa1HkxYL7m2gMByvqjL1JDvfbgbgY&m=3MTLR2gGXDKj69-pdUEb1Lox_flBpUAiV1N6__g8DeU&s=YTevS5Kk1BYJKI0CW499xv2PEqydV3z3C1bTV4nfIOo&e=>.

**********************************************************************
This e-mail message and all attachments transmitted with it may contain legally privileged and/or confidential information intended solely for the use of the addressee(s). If the reader of this message is not the intended recipient, you are hereby notified that any reading, dissemination, distribution, copying, forwarding or other use of this message or its attachments is strictly prohibited. If you have received this message in error, please notify the sender immediately and delete this message and all copies and backups thereof. Thank you.

**Comment by danieldorsey3** [comment]
@MOlausson -- 
We got the white screen again after trying to Reveal after team added their vote, so issue doesn’t appear to have been fixed. Please review and advise what is needed to review further. Thanks

**Comment by danieldorsey3** [comment]
@MOlausson --
from console log error -- 
react-dom.production.min.js:4408 TypeError: Cannot read properties of undefined (reading 'identifier')
    at t.n.renderCard (workItemView.tsx:200)
    at workItemView.tsx:133
    at Array.map (<anonymous>)
    at t.value (workItemView.tsx:127)
    at Oi (react-dom.production.min.js:3785)
    at Pi (react-dom.production.min.js:3776)
    at Di (react-dom.production.min.js:3960)
    at Ka (react-dom.production.min.js:5514)
    at Ga (react-dom.production.min.js:5536)
    at Os (react-dom.production.min.js:5958)
da @ react-dom.production.min.js:4408
n.callback @ react-dom.production.min.js:4773
oa @ react-dom.production.min.js:4271
ra @ react-dom.production.min.js:4259
za @ react-dom.production.min.js:4999
qa @ react-dom.production.min.js:5123
(anonymous) @ react-dom.production.min.js:5975
t.unstable_runWithPriority @ scheduler.production.min.js:274
Rs @ react-dom.production.min.js:5974
Os @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
Ns @ react-dom.production.min.js:6020
kn @ react-dom.production.min.js:1737
react-dom.production.min.js:5940 Uncaught TypeError: Cannot read properties of undefined (reading 'identifier')
    at t.n.renderCard (workItemView.tsx:200)
    at workItemView.tsx:133
    at Array.map (<anonymous>)
    at t.value (workItemView.tsx:127)
    at Oi (react-dom.production.min.js:3785)
    at Pi (react-dom.production.min.js:3776)
    at Di (react-dom.production.min.js:3960)
    at Ka (react-dom.production.min.js:5514)
    at Ga (react-dom.production.min.js:5536)
    at Os (react-dom.production.min.js:5958)
n.renderCard @ workItemView.tsx:200
(anonymous) @ workItemView.tsx:133
value @ workItemView.tsx:127
Oi @ react-dom.production.min.js:3785
Pi @ react-dom.production.min.js:3776
Di @ react-dom.production.min.js:3960
Ka @ react-dom.production.min.js:5514
Ga @ react-dom.production.min.js:5536
Os @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
Ns @ react-dom.production.min.js:6020
kn @ react-dom.production.min.js:1737


from issue log --
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown. 

affected resource --
ms.vss-web.platform-content.es6.NSbq23FcOw4zcRso.min.js:1

**Comment by danieldorsey3** [comment]
also got it again on a different PBI Estimate, the error looks a lil diff so posting it also --

@MOlausson --
from console log error --
react-dom.production.min.js:4408 TypeError: Cannot read properties of undefined (reading 'identifier')
    at t.n.renderCard (workItemView.tsx:200)
    at workItemView.tsx:133
    at Array.map (<anonymous>)
    at t.value (workItemView.tsx:127)
    at Oi (react-dom.production.min.js:3785)
    at Pi (react-dom.production.min.js:3776)
    at Di (react-dom.production.min.js:3960)
    at Ka (react-dom.production.min.js:5514)
    at Ga (react-dom.production.min.js:5536)
    at Os (react-dom.production.min.js:5958)
da @ react-dom.production.min.js:4408
n.callback @ react-dom.production.min.js:4773
oa @ react-dom.production.min.js:4271
ra @ react-dom.production.min.js:4259
za @ react-dom.production.min.js:4999
qa @ react-dom.production.min.js:5123
(anonymous) @ react-dom.production.min.js:5975
t.unstable_runWithPriority @ scheduler.production.min.js:274
Rs @ react-dom.production.min.js:5974
Os @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
Ns @ react-dom.production.min.js:6020
kn @ react-dom.production.min.js:1737
react-dom.production.min.js:5940 Uncaught TypeError: Cannot read properties of undefined (reading 'identifier')
    at t.n.renderCard (workItemView.tsx:200)
    at workItemView.tsx:133
    at Array.map (<anonymous>)
    at t.value (workItemView.tsx:127)
    at Oi (react-dom.production.min.js:3785)
    at Pi (react-dom.production.min.js:3776)
    at Di (react-dom.production.min.js:3960)
    at Ka (react-dom.production.min.js:5514)
    at Ga (react-dom.production.min.js:5536)
    at Os (react-dom.production.min.js:5958)
n.renderCard @ workItemView.tsx:200
(anonymous) @ workItemView.tsx:133
value @ workItemView.tsx:127
Oi @ react-dom.production.min.js:3785
Pi @ react-dom.production.min.js:3776
Di @ react-dom.production.min.js:3960
Ka @ react-dom.production.min.js:5514
Ga @ react-dom.production.min.js:5536
Os @ react-dom.production.min.js:5958
Ts @ react-dom.production.min.js:5925
Ns @ react-dom.production.min.js:6020
kn @ react-dom.production.min.js:1737

**Comment by MOlausson** [comment]
Cannot reproduce, closing for now but feel free to re-open @danieldorsey3 .

**Comment by danieldorsey3** [comment]
> @danieldorsey3 is this still a problem?

We have not experienced the issue recently, we have been able to use Estimate board. We use regularly as part of sprint ceremonies, and will advise if issue comes up. Thanks
